apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: deny-public-lbs
webhooks:
  - name: deny-public-services.questionable.services
    sideEffects: None
    rules:
      # This is an intentionally broad webhook configuration that is designed to
      # capture subresources as well, in order to correctly validate all possible
      # matches
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        operations:
          - "CREATE"
          - "UPDATE"
        resources:
          - "services"
    failurePolicy: Fail
    clientConfig:
      service:
        # This is the hostname our certificate needs in its Subject Alternative
        # Name array - name.namespace.svc
        # If the certificate does NOT have this name, TLS validation will fail.
        name: admission-control-service
        namespace: default
        path: "/admission-control/deny-public-load-balancers"
      # This should be the CA certificate from your Kubernetes cluster
      # Use the below to generate the certificate in a valid format:
      # $ kubectl config view --raw --minify --flatten \
      #   -o jsonpath='{.clusters[].cluster.certificate-authority-data}'
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQVB3S1JwRkJZdlZEQlJpRXVUNExrcDh3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05qUXhNMk14T0RndE9UUTVOUzAwT0dJNUxUZzRNVGt0WXpKaFpUTXlPREkzTkRjeQpNQjRYRFRFNU1EWXlNekl3TXpBek9Gb1hEVEkwTURZeU1USXhNekF6T0Zvd0x6RXRNQ3NHQTFVRUF4TWtOalF4Ck0yTXhPRGd0T1RRNU5TMDBPR0k1TFRnNE1Ua3RZekpoWlRNeU9ESTNORGN5TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdTdCa1JlM1VRWjNkaWQzaEl3a3ZmaXJNTUVNcCs3eEw4Uytrc3RkVgpVZEwrY0NQb01KeGluS25CZTA0Qmdzckp6bS96TWpMbmIrcTZBV0VFQTUxbk1jSnp2eWFSSFZkQmNsbU1zTlc2Cm95OC9vci9pWDhSNjYxcllUTlVibHFsa3JqSWNxRE9naGJNSzYwbUgzZnlmZlBZcmJUVUs3b3JiQlAvaitPdk8KcEFZYnNQTjh3R2hoZ2Q3K2pGL3JPWlN2amVHZHY0eG9UeUpMZU5QSzJJb3FrWWQ5eENLR2lMNktpaWhXbi9HYgozM3kzWkpJVVZucGFjdTNQODVNanJEVDJSam1vaklIRjgvWHh6VHQ0c2tXQUllZXV1MWhocDJ5WkFuRXRjUVR0CjMvSUIzYm84blJMaUxMRWJmZDJVcnE0ZzlEdkVFK1pOSEZuUFI3dE1POE5GVFFJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpsL2N5UDROVGVIdkUvT25DcTM3WlBqL2pMbWpsZVlUck1wZ0NrTk1DNG5oQ0c4R3pxTkZtQ3V6TmZWUGliMmYvCi9wSUhRSmZBTUxzWVg3NlpGQzFoMGE1Mm9Db0kzeFpScTVJTGNIWnRZOXAwYm5HQ2EzYUFEcnQ0OUZOVUN3N2QKYTdsOHgrQ3NGQk1lRlZ0dm96RnVaUE1uWnlxNkw1Y2swRnBNd2tQT1VwYjE5bjdQYW1QSGJSbkRVNThVQTlGbApHbkRZdGlBMGZJdFhnbDJwTjVCd1orNlRiOS9FdW1GOU5VQUMvV1ZkUGJ1VTBqK2RPcWwvelQyTHlsRndSVXUzCjVkUWxSRE5LVTgwY2pVSzlqd1Z2U0txVUtReHdFdTRHMWFwM3E2MDdFZFlSTVNuT2NOdzRSeDU2Qm5rdVo2V2oKZmNwQXF4Q2FTYkRqMVEyZk01eERadz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      # You can alternatively supply a URL to the service, as long as its reachable by the cluster.
      # url: ""
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: deny-ingresses
webhooks:
  - name: deny-ingresses.questionable.services
    sideEffects: None
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        operations:
          - "CREATE"
          - "UPDATE"
        resources:
          - "ingresses"
    failurePolicy: Fail
    clientConfig:
      service:
        name: admission-control-service
        namespace: default
        path: "/admission-control/deny-ingresses"
      # This should be the CA certificate from your Kubernetes cluster
      # Use the below to generate the certificate in a valid format:
      # $ kubectl config view --raw --minify --flatten \
      #   -o jsonpath='{.clusters[].cluster.certificate-authority-data}'
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQVB3S1JwRkJZdlZEQlJpRXVUNExrcDh3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05qUXhNMk14T0RndE9UUTVOUzAwT0dJNUxUZzRNVGt0WXpKaFpUTXlPREkzTkRjeQpNQjRYRFRFNU1EWXlNekl3TXpBek9Gb1hEVEkwTURZeU1USXhNekF6T0Zvd0x6RXRNQ3NHQTFVRUF4TWtOalF4Ck0yTXhPRGd0T1RRNU5TMDBPR0k1TFRnNE1Ua3RZekpoWlRNeU9ESTNORGN5TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdTdCa1JlM1VRWjNkaWQzaEl3a3ZmaXJNTUVNcCs3eEw4Uytrc3RkVgpVZEwrY0NQb01KeGluS25CZTA0Qmdzckp6bS96TWpMbmIrcTZBV0VFQTUxbk1jSnp2eWFSSFZkQmNsbU1zTlc2Cm95OC9vci9pWDhSNjYxcllUTlVibHFsa3JqSWNxRE9naGJNSzYwbUgzZnlmZlBZcmJUVUs3b3JiQlAvaitPdk8KcEFZYnNQTjh3R2hoZ2Q3K2pGL3JPWlN2amVHZHY0eG9UeUpMZU5QSzJJb3FrWWQ5eENLR2lMNktpaWhXbi9HYgozM3kzWkpJVVZucGFjdTNQODVNanJEVDJSam1vaklIRjgvWHh6VHQ0c2tXQUllZXV1MWhocDJ5WkFuRXRjUVR0CjMvSUIzYm84blJMaUxMRWJmZDJVcnE0ZzlEdkVFK1pOSEZuUFI3dE1POE5GVFFJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpsL2N5UDROVGVIdkUvT25DcTM3WlBqL2pMbWpsZVlUck1wZ0NrTk1DNG5oQ0c4R3pxTkZtQ3V6TmZWUGliMmYvCi9wSUhRSmZBTUxzWVg3NlpGQzFoMGE1Mm9Db0kzeFpScTVJTGNIWnRZOXAwYm5HQ2EzYUFEcnQ0OUZOVUN3N2QKYTdsOHgrQ3NGQk1lRlZ0dm96RnVaUE1uWnlxNkw1Y2swRnBNd2tQT1VwYjE5bjdQYW1QSGJSbkRVNThVQTlGbApHbkRZdGlBMGZJdFhnbDJwTjVCd1orNlRiOS9FdW1GOU5VQUMvV1ZkUGJ1VTBqK2RPcWwvelQyTHlsRndSVXUzCjVkUWxSRE5LVTgwY2pVSzlqd1Z2U0txVUtReHdFdTRHMWFwM3E2MDdFZFlSTVNuT2NOdzRSeDU2Qm5rdVo2V2oKZmNwQXF4Q2FTYkRqMVEyZk01eERadz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
